export enum tags {
  communities = "communities",
  attestations = "attestations",
  users = "users",
  profile = "profile",
  usersAnalytics = "users-analytics",
  analytics = "analytics",
  analyticsChartData = "analytics-chart-data",
  journals = "journals",
  journalApplications = "journal-applications",
  userEngagement = "user-engagement",
  publishingFunnel = "publishing-funnel",
  roStats = "ro-stats",
  retentionMetrics = "retention-metrics",
  researchObjectMetrics = "research-object-metrics",
}
